---
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name: Fix kvm
      run: >
        sudo sh -c 'echo "system-features = kvm" >> /etc/nix/nix.conf'
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build container image
      run: nix-build -A pushScript release.nix
    - name: Push image
      run: ./result --authfile "$DOCKER_CONFIG/config.json"
