---
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name: Fix kvm
      run: >
        sudo sh -c 'echo "system-features = kvm" >> /etc/nix/nix.conf'
    - name: Run a one-line script
      run: nix-build -A containerImage release.nix
